// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCascader: typeof import('element-plus/es')['ElCascader']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
}
export {}
